[package]
name = "rust_deps"
version = "0.1.0"
authors = ["DFINITY <support@dfinity.org>"]
edition = "2018"

[lib]
path = "main.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = { path = "../../../cdk-rs/src/ic-cdk", version = "0.1.1" }
ic-cdk-macros = { path = "../../../cdk-rs/src/ic-cdk-macros", version = "0.1.1" }
ic-types = "0.1.1"

