[package]
name = "ic-ledger-types"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Types for interacting with the ICP ledger canister."
homepage = "https://docs.rs/ic-ledger-types"
documentation = "https://docs.rs/ic-ledger-types"
readme = "README.md"
keywords = ["internet-computer", "ledger"]
categories = ["cryptography::cryptocurrencies", "data-structures"]
include = ["src", "Cargo.toml", "CHANGELOG.md", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk = { path = "../../src/ic-cdk", version = "0.10.0" }
candid = "0.9.0"
crc32fast = "1.2.0"
hex = "0.4"
serde = "1"
serde_bytes = "0.11"
sha2 = "0.9"
