[package]
name = "ic-ledger-types"
version = "0.6.0"
edition = "2021"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
description = "Types for interacting with the ICP ledger canister."
homepage = "https://docs.rs/ic-ledger-types"
documentation = "https://docs.rs/ic-ledger-types"
license = "Apache-2.0"
readme = "README.md"
keywords = ["internet-computer", "ledger"]
categories = ["cryptography::cryptocurrencies", "data-structures"]
include = ["src", "Cargo.toml", "CHANGELOG.md", "LICENSE", "README.md"]
repository = "https://github.com/dfinity/cdk-rs"
rust-version = "1.65.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk = { path = "../../src/ic-cdk", version = "0.9" }
candid = "0.8.0"
crc32fast = "1.2.0"
hex = "0.4"
serde = "1"
serde_bytes = "0.11"
sha2 = "0.9"
