[workspace]
members = ["src/counter_rs", "src/inter_rs", "src/inter2_rs"]

[workspace.dependencies]
candid = "0.9"
ic-cdk = { path = "../../src/ic-cdk" }
ic-cdk-macros = { path = "../../src/ic-cdk-macros" }
ic-cdk-bindgen = { path = "../../src/ic-cdk-bindgen" }
