[package]
name = "rust_profile"
version = "0.1.0"
authors = ["lsgunnlsgunn <lisa.s.gunn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.2.4"
ic-cdk-macros = "0.2.4"
ic-types = "0.1.1"
serde = "1.0.111"
