= Incrementing a counter
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc:
:toc: right
:toc-title: TUTORIAL - SIMPLE PERSISTENCE
:toclevels: 3
:proglang: Rust
:platform: Internet Computer platform
:LEE: local canister execution environment
:IC: Internet Computer blockchain
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:cdk-short-name: DFINITY Rust CDK
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust

In this tutorial, you are going to write a dapp that provides a few basic functions to increment a counter and illustrates the persistence of a value.

For this tutorial, the dapp declares a `+COUNTER+` as a mutable variable to contain a natural number that represents the current value of the counter.
This dapp supports the following functions:

* The `+increment+` function updates the current value, incrementing by 1 with no return value.
* The `+get+` function is a simple query that returns the current value of the counter.
* The `+set+` function updates the current value to the numeric value you specify as an argument.

This tutorial provides a simple example of how you can increment a counter by calling functions on a deployed canister smart contract.
By calling the function to increment a value multiple times, you can verify that the variable state—that is, the value of the variable between calls—persists.

Like the other sample dapps, this tutorial demonstrates a simple, but realistic, workflow in which you perform the following steps:

* Create a new project.
* Write a dapp that compiles into a WebAssembly module.
* Deploy the canister on the {LEE}.
* Invoke the canister smart contract methods to increment then read the value of a counter.

[[before-you-begin]]
== Before you begin

Before you start your project, verify the following:

* You have an internet connection and access to a shell terminal on your local macOS or Linux computer.

* You have downloaded and installed the Rust programming language and Cargo as described in the link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust installation instructions] for your operating system.

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
The Rust tool chain must be at version 1.46.0, or later.

* You have downloaded and installed the {sdk-long-name} package as described in link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].

* You have `+cmake+` installed. For example, use Homebrew with the following command:
+
[source,bash]
----
brew install cmake
----
For instructions on how to install Homebrew, see the link:https://docs.brew.sh/Installation[Homebrew Documentation].

* You have stopped any {LEE} processes running on your computer.

If you aren’t sure how to open a new terminal shell on your local computer, run commands in a terminal, or how to check for and install packages, see link:../quickstart/newcomers{outfilesuffix}[Preliminary steps for newcomers].
If you are comfortable meeting the prerequisites without instructions, continue to <<Create a new project,Create a new project>>.

This tutorial takes approximately 20 minutes to complete.

== Create a new project

To create a new project directory for this tutorial:

[arabic]
. Open a terminal shell on your local computer, if you don’t already have one open.
. Create a new project by running the following command:
+
[source,bash]
----
dfx new --type=rust rust_counter
----
+
. Change to your project directory by running the following command:
+
[source,bash]
----
cd rust_counter
----

== Modify the default project

In the link:rust-quickstart{outfilesuffix}[Hello, World! Rust CDK Quick Start], you went through the files in a default project with Rust type canister.

To complete this tutorial, you'll need to complete the following steps:

* <<Replace the default dapp>>
* <<Update interface description file>>

=== Replace the default dapp

Now that you have the files in place for your Rust dapp, we can replace the template `+lib.rs+` dapp with the Rust dapp we want to deploy on the {IC}.

To replace the default dapp:

. Check that you are still in the root directory for your project, if needed.
. Open the template `+src/rust_counter/lib.rs+` file in a text editor and delete the existing content.
+
The next step is to write a Rust dapp that declares the `+COUNTER+` variable and implements the `+increment+`, `+get+`, and `+set+` functions.
. Copy and paste the following sample code into the `+lib.rs+` file:
+
[source,motoko]
----
include::example$counter-tutorial/counter.rs[]
----
. Save your changes and close the `+lib.rs+` file to continue.

=== Update interface description file

Candid is an interface description language (IDL) for interacting with canisters running on the Internet Computer.
Candid files provide a language-independent description of a canister's interfaces including the names, parameters, and result formats and data types for each function a canister defines.

By adding Candid files to your project, you can ensure that data is properly converted from its definition in Rust to run safely on the {IC}.

To see details about the Candid interface description language syntax, see the link:../candid-guide/candid-intro{outfilesuffix}[_Candid Guide_] or the https://docs.rs/candid/[Candid crate documentation].

To update the Candid file for this tutorial:

. Check that you are still in the root directory for your project, if needed.
. Open the `+src/rust_counter/rust_counter.did+` file in a text editor, then copy and paste the following `+service+` definition for the `+increment+`, `+get+`, and `+set+` functions:
+
[source,did]
----
service : {
  "increment": () -> ();
  "get": () -> (nat) query;
  "set": (nat) -> ();
}
----
. Save your changes and close the `+rust_counter.did+` file to continue.

== Start the {LEE}

Before you can build the `+rust_counter+` project, you need to connect to the {LEE} running in your development environment or the decentralized {IC} mainnet.

To start the {LEE}:

. Check that you are still in the root directory for your project, if needed.
. Start the {LEE} on your computer in the background by running the following command:
+
[source,bash]
----
dfx start --background
----
+
Depending on your platform and local security settings, you might see a warning displayed.
If you are prompted to allow or deny incoming network connections, click *Allow*.

== Register, build, and deploy your project

After you connect to the {LEE} running in your development environment, you can register, build, and deploy your project locally.

To register, build, and deploy:

. Check that you are still in root directory for your project directory, if needed.
. Register, build, and deploy the canisters specified in the `+dfx.json+` file by running the following command:
+
[source,bash]
----
dfx deploy
----
+
The `+dfx deploy+` command output displays information about each of the operations it performs similar to the following excerpt:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_counter"...
"rust_counter" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "rust_counter_assets"...
"rust_counter_assets" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Executing: "cargo" "build" "--target" "wasm32-unknown-unknown" "--release" "-p" "rust_counter"
...
    Finished release [optimized] target(s) in 53.36s
Building frontend...
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "r7inp-6aaaa-aaaaa-aaabq-cai"
Installing code for canister rust_counter, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
...
Deployed canisters.
....

== Call functions and test the dapp

After successfully deploying the canister, you can test the canister by invoking the functions it provides.
For this tutorial:

* Call the `+get+` function to query the value of the counter.
* Call the `+increment+` function to increment the counter each time it is called.
* Call the `+set+` function to pass an argument to update the counter to an arbitrary value you specify.

To test the dapp:

[arabic]
. Call the `+get+` function to read the current value of the `+COUNTER+` variable by running the following command:
+
[source,bash]
----
dfx canister call rust_counter get
----
+
The command returns the current value of the `+COUNTER+` variable as zero:
+
....
(0 : nat)
....
[arabic]
. Call the `+increment+` function to increment the value of the `+COUNTER+` variable by one:
+
[source,bash]
----
dfx canister call rust_counter increment
----
+
This command increments the value of the variable—changing its state—but does not return the result.
. Rerun the command to call the `+get+` function to see the current value of the `+COUNTER+` variable:
+
[source,bash]
----
dfx canister call rust_counter get
----
+
The command returns the updated value of the `+COUNTER+` variable as one:
+
....
(1 : nat)
....
. Run additional commands to experiment with call the functions and using different values.
+
For example, try commands similar to the following to set and return the counter value:
+
[source,bash]
----
dfx canister call rust_counter set '(987)'
dfx canister call rust_counter get
----
+
Returns the current value of 987.
+
[source,bash]
----
dfx canister call rust_counter increment
dfx canister call rust_counter get
----
+
Returns the incremented value of 988.

== Stop the {LEE}

After you finish experimenting with your dapp, you can stop the local Internet Computer network so that it doesn’t continue running in the background.

To stop the {LEE}:

. In the terminal that displays network operations, press Control-C to interrupt the {LEE} process.

. Stop the {LEE} by running the following command:
+
[source,bash]
----
dfx stop
----
