= Adding and searching simple records
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc:
:toc: right
:toc-title: TUTORIAL - SAMPLE PROFILE
:toclevels: 3
:proglang: Rust
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust

In this tutorial, you are going to write a program that provides a few basic functions to add and retrieve simple profile records that consist of a name, description, and an array of keywords.

This program supports the following functions:

* The `+update+` function enables you to add a profile that consists of a `+name+`, a `+description+`, and `+keywords+`.
* The `+getSelf+` function returns the profile for the principal associated with the function caller.
* The `+get+` function performs a simple query to return the profile matching the `+name+` value passed to it.
For this function, the name specified must match the `+name+` field exactly to return the record.
* The `+search+` function performs a more complex query to return the profile matching all or part of the text specified in any profile field. For example, the `+search+` function can return a profile containing a specific keyword or that matches only part of a name or description.

This tutorial provides a simple example of how you can use the Rust CDK interfaces and macros to simplify writing programs in Rust for the {IC}.

This tutorial demonstrates:
* How to represent slightly more complex data—in the form of a profile as a `+record+` and an `+array+` of keywords—using the Candid interface description language.
* How to write a simple search function with partial string matching.
* How profiles are associated with a specific principal.

== Before you begin

Before starting the tutorial, verify the following:

* You have downloaded and installed the Rust programming language and Cargo as described in the link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust installation instructions] for your operating system.

* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart{outfilesuffix}#download-and-install[Download and install].

* You have downloaded the latest version of the {cdk-long-name} from the link:https://crates.io/[Rust community’s crate registry] or from the link:https://github.com/dfinity/cdk-rs[Rust CDK] repository.

* You have stopped any {IC} network processes running on the local
computer.

This tutorial takes approximately 20 minutes to complete.

== Create a new project

To create a new project directory for this tutorial:

[arabic]
. Open a terminal shell on your local computer, if you don’t already have one open.
. Change to the folder you are using for your {IC} sample projects.
. Create a new project by running the following command:
+
[source,bash]
----
dfx new rust_profile
----
+
The command creates a new `+rust_profile+` project and Git repository for your project.
. Change to your project directory by running the following command:
+
[source,bash]
----
cd rust_profile
----

== Modify the default configuration

In the link:rust-quickstart{outfilesuffix}[Rust Canister Developer Quick Start], you saw that creating a new project adds a default `+dfx.json+` configuration file to your project directory.

=== Edit canister settings

To modify the default `+dfx.json+` configuration file for a Rust project:

. Open the `+dfx.json+` configuration file in a text editor.
. Replace the `+canisters.rust_profile+` settings with settings for building a canister using the `+cargo build+` command.
+
For example, under the `+rust_profile+` key, replace the `+main+` and `+type+` settings with settings like these:
+
[source,json]
----
"build": "cargo build --target wasm32-unknown-unknown --package  rust_profile --release",
"candid": "src/rust_profile/profile.did",
"wasm": "target/wasm32-unknown-unknown/release/rust_profile.wasm",
"type": "custom"
}
----
. Remove all of the `+rust_profile_assets+` configuration settings from the file.
+
The sample program for this tutorial doesn't use any front-end assets, so you can remove those settings from the configuration file.
. Remove the `+defaults+` and `+dfx+` version settings.
+
For example, the configuration file looks like this after you modify the settings:
+
....
include::example$profile-tutorial/profile-dfx.json[]
....
. Save your change and close the `+dfx.json+` file to continue.

=== Add Cargo.toml settings to the project

To add `+Cargo.toml+` settings for the project:

. Check that you are still in the root directory for your project, if needed.
. Create a new file named `+Cargo.toml+` if you created the project using `+dfx+` or open the default `+Cargo.toml+` file if you created the project using Cargo.
. Use the [workspace] key to specify the source file directories for your program.
+
For example:
+
[source,toml]
----
[workspace]
members = [
    "src/rust_profile",
]
----
. Save your changes and close the `+Cargo.toml+` file to continue.

== Modify the default program

The next step is to replace the default source code in the `+src/rust_counter/main.mo+` file with a Rust program that implements the `+getSelf+`, `+update+`, `+get+`, and `+search+` functions.

To modify the default template source code:

. Check that you are still in the root directory for your project, if needed.
. Rename the default `+src/rust_profile/main.mo+` file to use the Rust file extension by running the following command:
+
[source,bash]
----
mv src/rust_profile/main.mo src/rust_profile/profile.rs
----
. Open the `+src/rust_profile/profile.rs+` file in a text editor and delete the existing content.
. Copy and paste the following sample code into the `+profile.rs+` file:
+
[source,motoko]
----
include::example$profile-tutorial/profile.rs[]
----
. Save your changes and close the file to continue.

=== Add required files to the source directory

Before you can build the Rust program, you must provide some additional settings in the source code directory.

To complete the environment for building Rust projects to be deployed on the {IC}, you need to do the following:

* Add a second `+Cargo.toml+` file for the program.
* Add a Candid interface description file to describe the type signatures for the program.

To add the required files:

. Change to the source code directory for your program.
+
For example:
+
[source,bash]
----
cd src/rust_profile
----
. Create a second file named `+Cargo.toml+` and open it in a text editor.
. Configure settings for your project.
+
For example, you should have a `+Cargo.toml+` file with settings similar to the following for this tutorial:
+
[source,toml]
----
include::example$profile-tutorial/profile-Cargo.toml[]
----
+
NOTE: Replace the path to the `+ic-cdk+` and `+ic-cdk-macros+` packages with the appropriate path for your local computer.

. Save your changes and close the `+Cargo.toml+` file to continue.
. Create a new file named `+profile.did+`.
. Open the file in a text editor, then copy and paste the following `+type+` declaration and `+service+` definition for the `+getSelf+`, `+update+`, `+get+`, and `+search+` functions:
+
[source,did]
----
include::example$profile-tutorial/profile.did[]
----
. Save your changes and close the `+profile.did+` file to continue.

== Start the network and deploy locally

Before you can build the `+rust_profile+` project, you need to connect to the {IC} network either running locally in your development environment or running remotely on a sub-network that you can access.

To start the network locally:

[arabic]
. Navigate back to the root directory of your project.
. Open a new terminal window or tab on your local computer.
+
For example, you can do either of the following if running Terminal on macOS:
+
--
* Click *Shell*, then select *New Tab* to open a new terminal in your current working directory.
* Click *Shell* and select *New Window*, then run `+cd ~/ic-projects/rust_counter+` in the new terminal if your `+rust_counter+` project is in the `+ic-projects+` working folder.
--
+
You should now have two terminals open with your project directory as your current working directory.
. Start the {IC} network on your local computer by running the following command:
+
[source,bash]
----
dfx start
----
+
After you start the local network, the terminal displays messages about network operations.
. Leave the terminal that displays network operations open.
. Switch to your second terminal window or tab.
. Register, build, and deploy the canister for the project by running the following command:
+
[source,bash]
----
dfx deploy
----

== Invoke functions on the deployed canister

After successfully deploying the canister, you can test the canister by invoking the functions it provides.
For this tutorial:

* Invoke the `+update+` function to add a profile.
* Invoke the `+getSelf+` function to display the profile for the principal identity.
* Invoke the `+search+` function to look up the profile using a keyword.

To test invoking methods on the deployed canister:

[arabic]
. Run the following command to invoke the `+update+` function to create a profile record:
+
[source,bash]
----
dfx canister call rust_profile update '(record {name = "Luxi"; description = "mountain dog"; keywords = vec {"scars"; "toast"}})'
----
. Run the following command to invoke the `+getSelf+` function to retrieve a profile record:
+
[source,bash]
----
dfx canister call rust_profile getSelf
----
+
The command returns the profile you used the `+update+` function to add.
For example:
+
....
(  record {
    name = "Luxi";
    description = "mountain dog";
    keywords = vec { "scars"; "toast" };
  },
)
....
+
In its current form, the program only stores and returns one profile. 
If you run the following command to add a second profile using the `+update+` function, the command replaces the `+Luxi+` profile with the `+Dupree+` profile:
+
[source,bash]
----
dfx canister call rust_profile update '(record {name = "Dupree"; description = "black dog"; keywords = vec {"funny tail"; "white nose"}})'
----
+
You can use the `+get+`, `+getSelf+`, and `+search+` functions, but they will only return results for the `+Dupree+` profile.
. Run the following command to invoke the `+search+` function:
+
[source,bash]
----
dfx canister call rust_profile search '("black")';
----
+
This command finds the matching profile using the `+description+` and returns the profile:
+
....
(
  opt record {
    name = "Dupree";
    description = "black dog";
    keywords = vec { "funny tail"; "white nose" };
  },
....

== Adding profiles for new identities

In its current form, the program only stores one profile—the one associated with the principal invoking the commands. TO test that the get, getSelf, and search functions do what we want them to, we need to add some new identities that can have different profiles.

To add identities for testing:

. Create a new user identity by running the following command:
+
[source,bash]
----
dfx identity new Miles
----
+
....
Creating identity: "Miles".
Created identity: "Miles".
....

. Call the `+update+` function to add a profile for the new identity.
+
[source,bash]
----
dfx --identity Miles canister call rust_profile update '(record {name = "Miles"; description = "Great Dane"; keywords = vec {"Boston"; "mantle"; "three-legged"}})'
----
. Call the `+getSelf+` function to view the profile associated with the `+default+` user identity.
+
[source,bash]
----
dfx canister call rust_profile getSelf
----
+
The command displays the profile currently associated with the default identity, in this example, the Dupree profile:
+
....
(
  record {
    name = "Dupree";
    description = "black dog";
    keywords = vec { "funny tail"; "white nose" };
  },
)
....
. Call the `+getSelf+` function using the `+Miles+` user identity by running the following command:
+
[source,bash]
----
dfx --identity Miles canister call rust_profile getSelf
----
+
The command displays the profile currently associated with the Miles identity, in this example:
+
....
(
  record {
    name = "Miles";
    description = "Great Dane";
    keywords = vec { "Boston"; "mantle"; "three-legged" };
  },
)
....
. Call the `+search+` function using part of the description or a keyword to further test the whether the correct profile is returned.
+
For example, to verify the `+Miles+` profile is returned, you might run the following command:
+
[source,bash]
----
dfx canister call rust_profile search '("Great")'
----
+
The command returns the `+Miles+` profile:
+
....
(
  opt record {
    name = "Miles";
    description = "Great Dane";
    keywords = vec { "Boston"; "mantle"; "three-legged" };
  },
)
....
. Call the `+search+` function to further test the whether the correct profile is returned.
+
For example, to verify the `+Dupree+` profile is returned, you might run the following command:
+
[source,bash]
----
dfx canister call rust_profile search '("black")'
----
+
The command returns the `+Dupree+` profile:
+
....
(
  opt record {
    name = "Dupree";
    description = "black dog";
    keywords = vec { "funny tail"; "white nose" };
  },
)
....

== Extending the sample program

This sample program only stores one profile for each unique user identity. If you were to extend this application by adding a second program for linking social connections to each users profile, you would be well on your way to recreating the LinkedUp sample application using Rust.

////
== Modify the project to include another program

In its current form, the program doesn't quite do what we want it to, but instead of modifying the existing program, let's expand its functionality by adding a second program that depends on this first one.
By adding a second program, we can demonstrate service interoperability and composability while reusing functions we've already defined.

The steps are similar to the ones you just completed.

To add another program to the project:

. Check that you are in the root directory for your project.
. Open the project `+dfx.json+` file in a text editor to add a new section for a second canister.
+
For this example, add a section for a canister named `+profile_interoperation+` that looks like this:
+
[source,bash]
----
    "profile_interoperation": {
      "type": "custom",
      "candid": "src/profile_interoperation/profile_inter.did",
      "wasm": "target/wasm32-unknown-unknown/debug/profile_interoperation.wasm",
      "build": "cargo build --target wasm32-unknown-unknown --package profile_interoperation",
      "dependencies": [
        "rust_profile"
      ]
    }
----
. Save your change and close the `+dfx.json+` file to continue.
. Open the `+Cargo.toml+` file that you created for the project and add the `+profile_interoperation+` package as a member.
+
For example:
+
[source,toml]
----
[workspace]
members = [
    "src/rust_profile",
    "src/profile_interoperation",
]
----
. Save your changes and close the `+Cargo.toml+` file to continue.
. Change to your project `+src+` directory and copy the `+rust_profile+` directory to create a new directory for the `+profile_interoperation+` program.
+
[source,toml]
----
cd src
cp -r rust_profile/ profile_interoperation
----
. Open the `+profile_interoperation/Cargo.toml+` file in a text editor and modify the package name.
+
[source,toml]
----
name = "profile_interoperation"
----
+
Optionally, you can change the name of the program from `+profile.rs+` or use the same name.
For the sake of this example, we'll change the path to `+lib.rs+` for the program that contains the profile_interoperation code.
+
[source,toml]
----
[lib]
path = "lib.rs"
----
. Save your changes and close the `+Cargo.toml+` file to continue.
. Rename the main program file from `+profile_interoperation/profile.rs+` to `+profile_interoperation/lib.rs+` by running the following command:
+
[source,bash]
----
mv profile_interoperation/profile.rs profile_interoperation/lib.rs
----
. Open the `+lib.rs+` file in a text editor and delete the existing content.
. Copy and paste the following sample code into the `+lib.rs+` file:
+
[source,rust]
----
include::example$intercanister-tutorial/profile-interoperation.rs[]
----
. Rename the Candid `+profile_interoperation/profile.did+` file to `+profile_inter.did+` by running the following command:
+
[source,rust]
----
mv profile_interoperation/profile.did profile_interoperation/profile_inter.did
----
. Open the `+profile_inter.did+` file in a text editor and modify the service description:
+
[source,candid]
----
type Profile_2 = record {
    "name": text;
    "description": text;
    "keywords": vec text;
};
type Profile = Profile_2;

service : {
    "getSelf": () -> (Profile_2);
    "get": (text) -> (Profile_2);
    "update": (Profile_2) -> ();
    "search": (text) -> (opt Profile_2);
}
----
. Save your changes and close the `+profile_inter.did+` file to continue.
. Register, build, and deploy the canister for the project by running the following command:
+
[source,bash]
----
dfx deploy
----

////

== Stop the local network

After you finish experimenting with your program, you can stop the local Internet Computer network so that it doesn’t continue running in the background.

To stop the local network:

. In the terminal that displays network operations, press Control-C to interrupt the local network process.

. Stop the {IC} network by running the following command:
+
[source,bash]
----
dfx stop
----
