= Hello, World! Rust CDK Quick Start
:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:toclevels: 3
:proglang: Rust
:platform: Internet Computer platform
:LEE: local execution environment
:IC: Internet Computer blockchain
:company-id: DFINITY
:cdk-short-name: DFINITY Rust CDK
:sdk-short-name: DFINITY Canister SDK
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[quick-start-intro]]
The {cdk-long-name} provides tools, sample code, and documentation to help you create dapps to run on the decentralized {IC} mainnet.
This _Hello, World! Rust CDK Quick Start_ assumes that you are installing the {cdk-short-name} for the first time.

To help you get started, this tutorial illustrates how to modify the traditional "Hello World" first dapp to use the {cdk-short-name}.
This simple dapp has just one function that prints text to a terminal, but it provides a good model for understanding the workflow when writing dapps in Rust that you want to deploy on the {IC}.

[[before-you-begin]]
== Before you begin

Before you start your project, verify the following:

* You have an internet connection and access to a shell terminal on your local macOS or Linux computer.

* You have downloaded and installed the Rust programming language and Cargo as described in the link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust installation instructions] for your operating system.

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
The Rust tool chain must be at version 1.46.0, or later.

* You have downloaded and installed the {sdk-long-name} package as described in link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].

* You have `+cmake+` installed. For example, use Homebrew with the following command:
+
[source,bash]
----
brew install cmake
----
+
For instructions on how to install Homebrew, see the link:https://docs.brew.sh/Installation[Homebrew Documentation].

* You have stopped any {LEE} processes running on your computer.

If you aren’t sure how to open a new terminal shell on your local computer, run commands in a terminal, or how to check for and install packages, see link:../quickstart/newcomers{outfilesuffix}[Preliminary steps for newcomers].
If you are comfortable meeting the prerequisites without instructions, continue to <<Create a new project,Create a new project>>.

[[create-a-new-project]]
== Create a new project

Applications for the {IC} start as **projects**.
You can create new projects for the {IC} using the {sdk-short-name}.
Because you are building this project to be deployed on the {IC}, this tutorial focuses on how to create, build, and deploy a Rust program by using the `+dfx+` parent command and its subcommands.

To create a new project using the {sdk-short-name}:

. Open a terminal shell on your local computer, if you don’t already have one open.
. Create a new project with rust canister named `+rust_hello+` by running the following command:
+
[source,bash]
----
dfx new --type=rust rust_hello
----
+
The `+dfx new --type=rust rust_hello+` command creates a new `+rust_hello+` project directory, template files, and a new `+rust_hello+` Git repository for your project.
. Change to your project directory by running the following command:
+
[source,bash]
----
cd rust_hello
----

== Take a look at the project

The project is ready to be compiled and deployed to the {IC}.
Before that, let's go through the project files.

=== `+dfx.json+`

One of the template files included in your project directory is a default `+dfx.json+` configuration file.
This file contains settings required to build a project for the {IC} much like the `+Cargo.toml+` file provides build and package management configuration details for Rust programs.

The configuration file should look like this:

....
include::example$hello-dfx.json[]
....

Notice that under the `+canisters+` key, you have some default settings for the `+rust_hello+` canister.

. `+"type": "rust"+` specifies that `+rust_hello+` is a `+rust+` type canister.

. `+"candid": "src/rust_hello/rust_hello.did"+` specifies the location of the Candid interface description file to use for the canister.

. `+"package": "rust_hello"+` specifies the package name of the Rust crate. It should be the same as in the crate `+Cargo.toml+` file.

=== `+Cargo.toml+`

In the root directory, there is a `+Cargo.toml+` file.

It defines a Rust workspace by specifying paths to each Rust crate.
A Rust type canister is just a Rust crate compiled to WebAssembly.
Here we have one member at `+src/rust_hello+` which is the only Rust canister.
[source,toml]
----
[workspace]
members = [
    "src/rust_hello",
]
----

=== `+src/rust_hello/+`

Now we are in the Rust canister. As any standard Rust crate, it has a `+Cargo.toml+` file which configures the details to build the Rust crate.

==== `+src/rust_hello/Cargo.toml+`

[source,toml]
----
[package]
name = "rust_hello"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
----

Notice the `+crate-type = ["cdylib"]+` line which is necessary to compile this rust program into WebAssembly module.

==== `+src/rust_hello/lib.rs+`

The default project has a simple `+greet+` function that uses the {cdk-short-name} `+query+` macro.

[source,rust]
----
#[ic_cdk::query]
fn greet(name: String) -> String {
    format!("Hello, {}!", name)
}
----

==== `+src/rust_hello/rust_hello.did+`

Candid is an interface description language (IDL) for interacting with canisters running on the Internet Computer.
Candid files provide a language-independent description of  a canister's interfaces including the names, parameters, and result formats and data types for each function a canister defines.

By adding Candid files to your project, you can ensure that data is properly converted from its definition in Rust to run safely on the {IC}.

To see details about the Candid interface description language syntax, see the link:../candid-guide/candid-intro{outfilesuffix}[_Candid Guide_] or the https://docs.rs/candid/[Candid crate documentation].

[source,did]
----
service : {
    "greet": (text) -> (text) query;
}
----

This definition specifies that the `+greet+` function is a `+query+` method which takes `+text+` data as input and returns `+text+` data.

[[start-the-local-network]]
== Start the {LEE}

Before you can build your project, you need to connect to the {LEE} running in your development environment or the decentralized {IC} mainnet.

To start the {LEE}:

[arabic]
. Check that you are still in the root directory for your project, if needed.
. Start the {LEE} on your computer in the background by running the following command:
+
[source,bash]
----
dfx start --background
----
+
Depending on your platform and local security settings, you might see a warning displayed.
If you are prompted to allow or deny incoming network connections, click *Allow*.

[[register-ids]]
== Register, build, and deploy your project

After you connect to the {LEE} running in your development environment, you can register, build, and deploy your project locally.

To register, build, and deploy:

. Check that you are still in root directory for your project directory, if needed.
. Make sure you have `wasm32-unknown-unknown` installed by running the command:
+
[source,bash]
rustup target add wasm32-unknown-unknown
+
. Register, build, and deploy the canisters specified in the `+dfx.json+` file by running the following command:
+
[source,bash]
----
dfx deploy
----
+
The `+dfx deploy+` command output displays information about each of the operations it performs similar to the following excerpt:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_hello"...
"rust_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "rust_hello_assets"...
"rust_hello_assets" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Executing: "cargo" "build" "--target" "wasm32-unknown-unknown" "--release" "-p" "rust_hello"
    Updating crates.io index
   Compiling unicode-xid v0.2.2
   ...
Building frontend...
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "r7inp-6aaaa-aaaaa-aaabq-cai"
Installing code for canister rust_hello, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
...
Deployed canisters.
....

////
== Optimize and test the dapp

At this point, you have a dapp compiled to WebAssembly that has not been optimized for deployment on the {IC}.

To optimize and test the resulting canister:

. Check that you are still in root directory for your project directory, if needed.
. Install the `+ic-cdk-optimizer+` crate by running the following command:
+
[source,bash]
----
cargo install ic-cdk-optimizer
----
+
This package optimizes your Rust code to reduce the size of the WebAssembly output to ensure your dapp can be uploaded as a canister.
. Create a release directory within the `+src/rust_hello+` directory by running the following command:
+
[source,bash]
----
mkdir -p src/rust_hello/target/wasm32-unknown-unknown/release/
----
. Optimize the code within the `+target/rust_hello+` directory by running the following command:
+
[source,bash]
----
ic-cdk-optimizer target/wasm32-unknown-unknown/release/rust_hello.wasm -o target/wasm32-unknown-unknown/release/rust_hello-opt.wasm
----
////

== Test the dapp

To test the deployed dapp locally:

. Check that you are still in root directory for your project directory, if needed.
. Call the `+greet+` function in the dapp by running the following command:
+
[source,bash]
----
dfx canister call rust_hello greet world
----
. Verify that the call to the `+rust_hello+` canister `+greet+` function returns a text message `+("Hello, world!")+`.

== Stop the {LEE}

After testing the application, you can stop the {LEE} so that it doesn’t continue running in the background.

To stop the {LEE}:

. In the terminal that displays network operations, press Control-C to interrupt the {LEE} process.

. Stop the {LEE} running on your computer by running the following command:
+
[source,bash]
----
dfx stop
----
