[package]
name = "rust_counter"
version = "0.1.0"
authors = ["DFINITY <support@dfinity.org>"]
edition = "2018"

[lib]
path = "counter.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = { version = "0.2.4" }
ic-cdk-macros = { version = "0.2.4" }
ic-types = "0.1.1"
lazy_static = "1.4.0"
