[workspace]
members = ["src/profile_rs", "src/profile_inter_rs"]

[workspace.dependencies]
candid = "0.9"
ic-cdk = { path = "../../src/ic-cdk" }
ic-cdk-bindgen = { path = "../../src/ic-cdk-bindgen" }
serde = "1"
