[workspace]
members = [
    "src/profile_rs",
    "src/profile_inter_rs",
]

[patch.crates-io]
candid = { git = "https://github.com/dfinity/candid.git", rev = "73a8af2096093129274b23347be0c012e2362655"}
