on: [push, pull_request]
name: Publish Cargo docs
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust
      run: |
        rustup update ${{ matrix.rust }} --no-self-update
        rustup default ${{ matrix.rust }}
    - name: Build Docs
      run: |
        cargo doc --no-deps
         # Add an index.html for the root of the netlify docs.
        rustdoc README.md --output target/doc && mv target/doc/README.html target/doc/index.html

    - if: github.ref == 'refs/heads/master'
      name: Deploy to Netlify (master only)
      uses: South-Paw/action-netlify-deploy@v1.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: target/doc/
        comment-on-commit: true

    - if: github.ref != 'refs/heads/master'
      name: Deploy draft to Netlify
      uses: South-Paw/action-netlify-deploy@v1.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: target/doc/
        draft: true
        comment-on-pull-request: true
